7.14. Добро пожаловать, или посторонним вход воспрещён (часть 1)
htmlacademy-react/1157649-six-cities-8 pull request #10
Opened 2021-11-02 12:59 UTC by ivanna-humeniuk

2021-11-03 22:05 UTC, Saionaro requested changes
Отличная работа! Авторизация работает хорошо :)
От меня кучка мелочей, которые можно подправить для наведения красоты

2021-11-03 22:05 UTC, Saionaro commented on project/src/utills/snake-case-adapter.ts
> +export const snakeCaseAdapter = (item: RawOffer): Offer => ({
Почти хорошо, однако функция все равно не содержит глагол :)

2021-11-04 08:14 UTC, ivanna-humeniuk commented on project/src/components/login-screen/login-screen.tsx
> +const regExp = new RegExp(/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{2,}$/);
спасибо за инфу, буду знать))

2021-11-04 09:03 UTC, ivanna-humeniuk commented on project/src/store/reducers/offer-reducer.ts
> +  offer: null,
только loading заменила на isLoading

2021-11-04 09:39 UTC, ivanna-humeniuk commented on project/src/utills/is-checked-auth.ts
> +export const isCheckedAuth = (authorizationStatus: AuthorizationStatus): boolean =>
Она проверяет состояние, когда мы не знаем еще залогинен пользователь или нет.
Я заменила название на **checkIfAuthUnknown**.

2021-11-04 10:15 UTC, ivanna-humeniuk commented on project/src/components/property-screen/property-screen.tsx
> +  if(offerLoading || !offer) {
забрала проверку на offer, теперь если что то будет не так, то произойдет редирект на главную страницу)

2021-11-05 19:09 UTC, Saionaro approved these changes
Отлично поработала, молодец! Смотри какие редьюссеры стройные стали :)

Посмотри штуку с `authStatus` - возможно не только в этом месте нужно подравить.

2021-11-05 19:09 UTC, Saionaro commented on project/src/components/reviews/reviews.tsx
> +      {authStatus && <ReviewForm/>}
`authStatus` у нас теперь не boolean - нужно сравнивать конкретно с енумом `AuthStatus.Auth`

2021-11-05 19:09 UTC, merged

2021-11-05 19:35 UTC, ivanna-humeniuk commented on project/src/components/reviews/reviews.tsx
> +      {authStatus && <ReviewForm/>}
поправила)