7.15. Добро пожаловать, или посторонним вход воспрещён (часть 2)
htmlacademy-react/1157649-six-cities-8 pull request #11
Opened 2021-11-05 19:51 UTC by ivanna-humeniuk

2021-11-06 13:31 UTC, Saionaro requested changes
Хорошая работа, почти все отлично!
Обнаружил одну проблему - при попытке открыть несуществующее предложение по аренде - случается редирект на главную, по заданию нужна 404 страница.

2021-11-06 13:31 UTC, Saionaro commented on project/src/store/api-actions.ts
> +export const fetchReviewAction = (id: string, review: ReviewPost): ThunkActionResult =>
`submitReviewAction` ? Мы же тут его не загружаем, а отправляем на сервер.

Еще, может быть нам и не нужно ничего принимать в параметрах - у нас все данные (offer.id и review) есть в redux. Давай их оттуда и возьмем.

2021-11-06 13:31 UTC, Saionaro commented on project/src/store/reducers/offer-reducer.ts
> +          ...state.review,
А нужно ли деструктуризировать сюда старое review, если мы все там заменяем?
Как насчет просто ```review: {...action.payload}``` ?

2021-11-06 13:31 UTC, Saionaro commented on project/src/types/offers.ts
> +  id: number;
👍

2021-11-06 13:31 UTC, Saionaro commented on project/src/components/review-form/review-form.tsx
> +        checked={String(review.rating) === `${ratingLabels.length - index}`}
А рейтинг сейчас всегда число?
Если так, то зачем приводить к строке оба значения?

2021-11-06 13:31 UTC, Saionaro commented on project/src/components/review-form/review-form.tsx
> +  const isInvalid = !(review && review.comment.length >= REVIEW_MIN_LENGTH && review.comment.length <= REVIEW_MAX_LENGTH) || !review.rating;
Может быть в небольшую функцию унесем? Не в отдельный файл, а просто здесь выше:
```typescript
type isValidComment = (review: ReviewPost) => boolean;
```

2021-11-06 16:21 UTC, ivanna-humeniuk commented on project/src/components/review-form/review-form.tsx
> +        checked={String(review.rating) === `${ratingLabels.length - index}`}
переделала

2021-11-07 15:26 UTC, Saionaro requested changes
Спасибо за правки! Осталась одна небольшая, но важная проблема - нужно поправить получения стейта в `submitReviewAction`.

2021-11-07 15:26 UTC, Saionaro commented on project/src/store/api-actions.ts
> +    const {offer, review} = store.getState().offer;
Не совсем - для получения стейта у нас есть второй параметр - функция `_getState`.
Архитектурно неправильно в отдельном редьюссере импортировать store в целом - у нас получается "циклическая зависимость" - store зависит от редьюссера, а редьюссер от store.

2021-11-08 20:28 UTC, Saionaro approved these changes
То что надо!

2021-11-08 20:28 UTC, merged