6.7. Контроль и ограничения (часть 2)
htmlacademy-react/1157649-six-cities-8 pull request #12
Opened 2021-11-05 20:25 UTC by ivanna-humeniuk

2021-11-06 14:35 UTC, Saionaro requested changes
О, мне с самого начала этот торчащий дропдаун глаза мозолил :)
Почти все хорошо - но обнаружилась ошибка в закрытии дропдауна, а так же у меня предложение по рефакторингу сортировки в редьюссере

2021-11-06 14:35 UTC, Saionaro commented on project/src/components/sort/sort.tsx
> +    function handleOutsideClick(event: MouseEvent) {
Похоже, что закрытие по клику вне дропдауна сейчас не работает - посмотри, пожалуйста.
А еще, мб добавим закрытие по esc? :)

2021-11-06 14:35 UTC, Saionaro commented on project/src/store/reducers/offers-reducer.ts
> +            filteredList: state.filteredList.sort((offerA, offerB ) => offerA.price - offerB.price),
Давай реализуем сохранение выбранной сортировки при переключении между городами.
А так же немного причешем тут.
Я бы предложил создать функцию в духе
```ts
type pickSortFunction = (sorting: SortOptions) => function;
```
она по варианту сортировки возвращает нужную функцию для передачи в `sort()` - например
```ts
const sortByPriceToHigh = (offerA, offerB) => offerA.price - offerB.price;
```
вынеси их все выше.

Далее везде, где фигурирует filteredList - делаем и `filter` и `sort` - по данным, которые лежат в redux (`sortedOption` и `city`).

2021-11-06 17:43 UTC, ivanna-humeniuk commented on project/src/components/sort/sort.tsx
> +    function handleOutsideClick(event: MouseEvent) {
поправила, esc добавила)

2021-11-08 21:00 UTC, Saionaro approved these changes
Как ты ловко порешала конфликт, пока я завершал ревью :D

Все хорошо :)
Посмотри мои предложения по улучшению - в первую очередь имеет смысл поработать над оптимизацией подписок

2021-11-08 21:00 UTC, merged

2021-11-09 07:56 UTC, ivanna-humeniuk commented on project/src/components/sort/sort.tsx
>    useEffect(() => {
спасибо за подсказку, как отслеживать активные подписки =)