Обратная сторона реальности
htmlacademy-react/1157649-six-cities-8 pull request #5
Opened 2021-10-15 08:20 UTC by ivanna-humeniuk

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/8/user/1157649/tasks/5)

2021-10-16 17:37 UTC, Saionaro requested changes
Спасибо за работу, отличный старт!
Есть несколько важных правок и ряд предложений по улучшению от меня. Поработаем над заданием еще немного?

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/reviews-form/reviews-form.tsx
> +function ReviewsForm(): JSX.Element {
Почему во множественном числе?

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/favorites-screen/favorites-screen.tsx
> +  const {offers} = props;
Как насчет для `FavoritesScreen` сделать prop `listings`?
Примерно такой тип:
```
interface Listing {
   id: number;
   title: string;
   places: Offer[]; // кстати, удачное ли название для типа места - Offer?
}
```

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/place-card/place-card.tsx
> +import {Link} from 'react-router-dom';
Бывает, что принято сортировать и группировать импорты, например:
- сначала импорты сторонних библиотек
- потом глобальные импорты файлов проекта
- потом относительные импорты файлов проекта
- импорты css

Порой группы импортов даже разделяют пустыми строками.

Однако у нас все это совсем не обязательно, просто не удивляйся, если встретится где-то

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/reviews/reviews.tsx
> +          const ratingWidth = review.rating > 0 ? { width: `${review.rating * 20}%` } : { width: '0%'};
Напрашивается `useMemo` - так как создание объекта и передача его в props.
Однако у нас тут `map` - мы здесь не можем использовать хуки (1е правило хуков - помнишь?). А следовательно, нужно выделить `review` в отдельный компонент и уже там сделать `useMemo`.

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/reviews/reviews.tsx
> +                <time className="reviews__time" dateTime="2019-04-24">April 2019</time>
Полагаю, дату тоже нужно взять из `review`.

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +    return <Redirect to={AppRoute.Main}/>;
👍

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +  const data = offers.filter((item) => item.id === Number(slug));
Тут по смыслу лучше подойдет `.find()` - ведь нас интересует только один элемент, есть он или нет.

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +  const {title, description, bedrooms, host, goods, maxAdults, type, rating, price, isFavorite, isPremium} = data[0];
Тут так же как в карточке - возможно не стоит деструктуризировать все свойства из данных.
Свойства будут добавляться в будущем, строчка деструктуризации будет расти и расти - выглядит громоздко и сложно для восприятия. Просто обращайся через точку `data[0].maxAdults`

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +  const ratingWidth = rating > 0 ? {width: `${rating * 20}%`} : {width: '0%'};
`useMemo`

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +                  className={`property__bookmark-button ${isFavorite && 'property__bookmark-button--active'} button`}
А ты использовала раньше пакет [classnames](https://www.npmjs.com/package/classnames)? Посмотри, может быть тебе будет удобно использовать его в проекте

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +                  {bedrooms} Bedrooms
Предусмотрим единственную спальню?

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +                  {goods && goods.map((good) => (
То что надо 👌

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +                    className={`property__avatar-wrapper ${host?.isPro && 'property__avatar-wrapper--pro'} user__avatar-wrappe`}
```suggestion
                    className={`property__avatar-wrapper ${host?.isPro && 'property__avatar-wrapper--pro'} user__avatar-wrapper`}
```

2021-10-16 17:37 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
>                  <div className="property__host-user user">
Может быть, если `host` отсутствует, то просто не рисовать весь этот блок? Тогда избавимся от всех условных обращений.

2021-10-20 18:03 UTC, Saionaro commented on project/src/components/review-item/review-item.tsx
> +function ReviewItem({rating, user, id, comment, date}: ReviewProps): JSX.Element {
В целом, я бы предложил здесь поступить так же, как с компонентом карточки - сгруппировать все данные в объекте - review, например. Аргументы те же :)

2021-10-20 18:05 UTC, Saionaro commented on project/src/components/review-item/review-item.tsx
> +  const ratingWidth = rating > 0 ? { width: `${rating * 20}%` } : { width: '0%'};
Вот тут еще `useMemo` имеет смысл добавить (создание объекта для передачи в props)

2021-10-20 18:06 UTC, Saionaro commented on project/src/components/reviews/reviews.tsx
> +function Reviews({reviews}: ReviewsProps): JSX.Element {
Какой лаконичный компонент вышел :)

2021-10-20 18:12 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +  const bookmarkBtnClasses = classnames({
Круто, что вынесла конструирование классов здесь отдельно - так удобнее для восприятия.

2021-10-20 18:12 UTC, Saionaro commented on project/src/components/property-screen/property-screen.tsx
> +                        src={data.host?.avatarUrl}
Теперь, полагаю, можно убрать вопросики

2021-10-20 18:16 UTC, merged

2021-10-21 16:00 UTC, ivanna-humeniuk commented on project/src/components/property-screen/property-screen.tsx
> +  const bookmarkBtnClasses = classnames({
спасибо =)