Истина где-то на сервере
htmlacademy-react/1157649-six-cities-8 pull request #9
Opened 2021-10-29 13:03 UTC by ivanna-humeniuk

---
:mortar_board: [Истина где-то на сервере](https://up.htmlacademy.ru/react/8/user/1157649/tasks/10)

2021-10-30 16:52 UTC, Saionaro requested changes
Отличная работа! Очень аккуратно получилось :)
У меня в основном всякие мелочи по именованию, форматированию и предложения по улучшению.

Кстати, как насчет добавить прокрутку в начало страницы при переходе по ссылкам в `Other places in the neighbourhood`?

2021-10-30 16:52 UTC, Saionaro commented on project/src/components/reviews/reviews.tsx
> +import {AuthorizationStatus} from '../../const';
В принципе можно уже в `redux` завести флажок состояния аутентификации - пока что просто установить в `true` - и перейти на использование `redux`, вместо константы

2021-10-30 16:52 UTC, Saionaro commented on project/src/const.tsx
> +export const OFFERS_LOAD_FAIL_MESSAGE = 'Something went wrong, please try again!';
А кнопка, чтобы `try again` есть? :)

2021-10-30 16:52 UTC, Saionaro commented on project/src/const.tsx
> +  Offers = '/hotels',
👍

2021-10-30 16:52 UTC, Saionaro commented on project/src/index.tsx
> +  composeWithDevTools(applyMiddleware(thunk.withExtraArgument(api)), applyMiddleware(redirect)),
Тут можно чуть-чуть упростить - `applyMiddleware` принимает много миддлваров:
https://github.com/reduxjs/redux/blob/master/src/applyMiddleware.ts#L61

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/api-actions.ts
> +      toast.info(OFFERS_LOAD_FAIL_MESSAGE);
👍

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/api-actions.ts
> +      const mapper:OfferMapper<APIOffer> = new OfferSnakeCaseMapper();
Если честно, я бы предложил этот адаптер реализовать просто как utills-функцию, которой ты бы передала предложение с сервера, а она бы вернула преобразованное.
Выглядит, что ему незачем быть именно классом в данном случае.

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/reducer.ts
> +  offer: {} as Offer,
Неа. Не честно :)
Пусть будет `null` по-умолчанию. В экране предложения обработаем соответствующе

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/reducer.ts
> +    case ActionType.LoadOffers:
Полагаю, что лучше будет название действие `SetOffers` - ведь само оно ничего не загружает.

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/reducer.ts
> +    case ActionType.LoadOffer:
И вот тут `Set...`

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/reducer.ts
> +    case ActionType.LoadNearbyOffers:
И здесь `Set...`

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/reducer.ts
>  const initialState = {
Есть дополнительный критерий на разделение редьюсеров на более мелкие.
https://up.htmlacademy.ru/react/8/criteries#d18
Когда будешь добавлять новые данные, подумай, как можно будет их разбить, и, возможно, стоит сразу начать это делать.

2021-10-30 16:52 UTC, Saionaro commented on project/src/types/offers.ts
> +export type APIOffer = {
Еще такие данные из API, которые потом преобразуются в другой формат, иногда называют `Raw...` - `RawOffer`, например. `Сырые` данные мол.

2021-10-30 16:52 UTC, Saionaro commented on project/src/types/offers.ts
> +
```suggestion
```

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/middlewares/redirect.ts
> +export const redirect: Middleware<unknown, Reducer> =
Какая мудрёная штука :)

2021-10-30 16:52 UTC, Saionaro commented on project/src/services/api.ts
> +const URL_API = 'https://8.react.pages.academy/six-cities';
Вот эти две константы давай перенесем в соответствующий файл

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/api-actions.ts
> +import {toast} from 'react-toastify';
Классно, что отделила от обычных `action`!

2021-10-30 16:52 UTC, Saionaro commented on project/src/store/api-actions.ts
> +      const {data} = await api.get<APIOffer[]>(APIRoute.Offers);
Асинхронные действия часто еще окружают флажками.
Заводят в redux поле - `offersLoading`, перед началом загрузки делают `dispatch` - `offersLoading:true`, после окончания загрузки - `offersLoading:false` - и так на каждое асинхронное действие.

Потом это удобно использовать во всякие спиннерах загрузки в разных компонентах

2021-11-01 07:56 UTC, ivanna-humeniuk commented on project/src/const.tsx
> +export const OFFERS_LOAD_FAIL_MESSAGE = 'Something went wrong, please try again!';
заменила на 'Something went wrong, please reload page!'

2021-11-01 08:22 UTC, ivanna-humeniuk commented on project/src/store/reducer.ts
> +  offer: {} as Offer,
не прокатило =)

2021-11-01 09:53 UTC, ivanna-humeniuk commented on project/src/store/reducer.ts
>  const initialState = {
окей, я уже тогда разобью в следующем задании **7.14. Добро пожаловать, или посторонним вход воспрещён (часть 1)**

2021-11-01 09:54 UTC, ivanna-humeniuk commented on project/src/store/api-actions.ts
> +      const {data} = await api.get<APIOffer[]>(APIRoute.Offers);
Флажки добавлю в следующем задании, там как раз и разобью редьюсеры.

2021-11-01 09:56 UTC, ivanna-humeniuk commented on project/src/store/middlewares/redirect.ts
> +export const redirect: Middleware<unknown, Reducer> =
стащила с демо-проекта =)

2021-11-01 20:04 UTC, Saionaro approved these changes
Молодец! Отлично расправилась с комментариями!
Хорошо, что поправила переменные для классов везде, где дотянулась и спасибо за скролл :)

У меня есть предложения только по `project/src/utills/snakeCaseMapper.ts` - поработать с названиями. В остальном все круто

2021-11-01 20:05 UTC, merged